# Generated by Django 4.2 on 2025-12-27 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('is_scrapped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('Corrective', 'Corrective'), ('Preventive', 'Preventive')], max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Repaired', 'Repaired'), ('Scrap', 'Scrap')], default='New', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceteam')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceteam'),
        ),
    ]
